name: egnn-transformer
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - tqdm
  - torch_geometric
  - lightning
  - jax # need to adjust versions [cuda] or [cpu]
  - flax