name: egnn-transformer
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
  - nvidia # Only if you have CUDA-support
dependencies:
  - pytorch
  - pytorch-cuda==11.8 # Only if you have CUDA-support
  - nvidia::cudatoolkit # Only if you have CUDA-support
  - tqdm
  - lightning
  - rdkit
  - pip
  - pip:
    - "jax[cpu]"
    - torch_geometric
    - flax
