name: egnn-jax
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pytorch
  - tqdm
  - lightning
  - rdkit
  - pip
  - tensorboard
  - pip:
    - "jax[cpu]"
    - torch_geometric
    - flax
    - jraph
